name: perception
channels:
  - nvidia
  - pytorch
  - conda-forge
#  - defaults
#  - zimmf  # For cudatoolkit on M1/M2/MX Mac
dependencies:
  - python
  - pip
  - numpy<2.0.0
  - pandas
  - scikit-learn
  - scikit-image
  - pytorch
  - torchvision
  - cudatoolkit
  - cudnn
  - cudatoolkit-dev
  - opencv
  - matplotlib
  - pyyaml
  - ruff
  - python-dotenv
  - ultralytics
  - tensorboard
  - timm
  - tabulate

  - pip:
    - roboflow
    - boxmot
    - screeninfo
