name: perception
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - cudatoolkit
  - opencv
  - matplotlib
  - seaborn
  - pyyaml
  - ruff
  - python-dotenv
  - ultralytics
  - pip:
    - tensorboard
    - torch-tb-profiler
    - tensorboard-plugin-profile
    - sort-track
    - deep-sort-realtime
