alpha_beta_ratio_1: 0.97
alpha_beta_ratio_2: 0.26
cyc_fuse_score: false
cyc_match_final_thresh: 0.35
cyc_match_second_thresh: 0.44999999999999996
cyc_match_thresh: 0.74
cyc_new_track_thresh: 0.26
cyc_remove_stationary: true
cyc_track_buffer: 422
cyc_track_high_thresh: 0.33999999999999997
cyc_track_low_thresh: 0.99
ped_fuse_score: false
ped_match_final_thresh: 0.32999999999999996
ped_match_second_thresh: 0.41
ped_match_thresh: 0.5
ped_new_track_thresh: 0.86
ped_remove_stationary: true
ped_track_buffer: 234
ped_track_high_thresh: 0.71
ped_track_low_thresh: 0.44
