alpha: 0.9
alpha_second: 0.7
beta: 0.1
beta_second: 0.3
fuse_score: true
match_final_thresh: 0.8
match_second_thresh: 0.6
match_thresh: 0.7
new_track_thresh: 0.6
remove_stationary: true
track_buffer: 500
track_high_thresh: 0.7
track_low_thresh: 0.4