alpha: 0.7
alpha_second: 0.6
beta: 0.3
beta_second: 0.4
fuse_score: true
match_final_thresh: 0.7
match_second_thresh: 0.6
match_thresh: 0.8
max_avg_velocity_x: 310.1
max_avg_velocity_y: 130.1
new_track_thresh: 0.3
remove_stationary: true
track_buffer: 500
track_high_thresh: 0.5
track_low_thresh: 0.2