alpha: 0.7
alpha_second: 0.6
beta: 0.3
beta_second: 0.4
fuse_score: false
match_final_thresh: 0.27
match_second_thresh: 0.83
match_thresh: 0.64
new_track_thresh: 0.14
remove_stationary: true
track_buffer: 45
track_high_thresh: 0.23
track_low_thresh: 0.87