alpha: 0.75
alpha_second: 0.95
beta: 0.25
beta_second: 0.05
fuse_score: true
match_final_thresh: 0.7
match_second_thresh: 0.58
match_thresh: 0.97
new_track_thresh: 0.76
remove_stationary: true
track_buffer: 432
track_high_thresh: 0.77
track_low_thresh: 0.4