alpha: 0.7
alpha_second: 0.6
beta: 0.3
beta_second: 0.4
fuse_score: true
match_final_thresh: 0.4
match_second_thresh: 0.3
match_thresh: 0.8
new_track_thresh: 0.3
remove_stationary: False
track_buffer: 500
track_high_thresh: 0.5
track_low_thresh: 0.2