alpha: 0.7
alpha_second: 0.6
beta: 0.3
beta_second: 0.4
fuse_score: true
match_final_thresh: 0.83
match_second_thresh: 0.55
match_thresh: 0.7
new_track_thresh: 0.2
remove_stationary: true
track_buffer: 500
track_high_thresh: 0.7
track_low_thresh: 0.2