alpha: 0.6
alpha_second: 1.2
beta: 0.4
beta_second: 0.9
fuse_score: true
match_final_thresh: 0.7
match_second_thresh: 0.6
match_thresh: 0.8
max_avg_velocity_x: 150
max_avg_velocity_y: 35
new_track_thresh: 0.4
track_buffer: 4
track_high_thresh: 0.8
track_low_thresh: 0.3
remove_stationary: True
