alpha: 0.95
alpha_second: 0.7
beta: 0.05
beta_second: 0.3
fuse_score: true
match_final_thresh: 0.7
match_second_thresh: 0.58
match_thresh: 0.95
new_track_thresh: 0.7
remove_stationary: true
track_buffer: 200
track_high_thresh: 0.77
track_low_thresh: 0.4