alpha: 0.8
alpha_second: 0.5
beta: 0.2
beta_second: 0.5
fuse_score: true
match_final_thresh: 0.7
match_second_thresh: 0.5
match_thresh: 0.9
new_track_thresh: 0.7
remove_stationary: False
track_buffer: 40
track_high_thresh: 0.77
track_low_thresh: 0.4