alpha: 0.3
alpha_second: 0.7
beta: 0.7
beta_second: 0.3
fuse_score: true
match_final_thresh: 0.83
match_second_thresh: 0.6
match_thresh: 0.7
new_track_thresh: 0.3
remove_stationary: false
track_buffer: 20
track_high_thresh: 0.6
track_low_thresh: 0.4