# Paths to raw and rectified sequences
data:
  raw_sequences_path:
    - "data/34759_final_project_raw/seq_01/"
    - "data/34759_final_project_raw/seq_02/"
    - "data/34759_final_project_raw/seq_03/"
  rect_sequences_path:
    - "data/34759_final_project_rect/seq_01/"
    - "data/34759_final_project_rect/seq_02/"
    - "data/34759_final_project_rect/seq_03/"
  calibration_file: "data/34759_final_project_raw/calib_cam_to_cam.txt"
  rectified_images_path: "data/34759_final_project_rect/rectified_images/"
  label_files:
    - ""  # Sequence 0 (if sequences start from 1)
    - "data/34759_final_project_rect/seq_01/labels.txt"  # Sequence 1
    - "data/34759_final_project_rect/seq_02/labels.txt"  # Sequence 2
    - ""  # Sequence 3 (no labels)

# Calibration parameters
calibration:
  chessboard_size: [9, 6]
  square_size: 0.01  # in meters
  calibration_file_rect: "data/34759_final_project_rect/calib_cam_to_cam.txt"

# Detection parameters
detection:
  classification:
    model_path: "yolo11m-seg.pt"  # Ensure this model exists or use a valid path
  device: "cuda:0"  # or "cuda:0" if using GPU
  confidence_threshold: 0.4
  nms_threshold: 0.3
  class_names:
    - "person"
    - "car"
    - "bicycle"

# Tracking parameters
tracking:
  max_age: 60
  min_hits: 3
  dt: 1.0

# Stereo matching parameters
stereo:
  min_disparity: 0
  num_disparities: 160
  block_size: 7
  disp12_max_diff: 1
  uniqueness_ratio: 15
  speckle_window_size: 100
  speckle_range: 32
  pre_filter_cap: 63

# Logging configuration
logging:
  config_file: "config/logging.yaml"

# Processing options
processing:
  use_rectified_data: true  # Set to false to process raw data
