# config/config.yaml
data:
  raw_sequences_path: ["data/34759_final_project_raw/seq_01/", "data/34759_final_project_raw/seq_02/", "data/34759_final_project_raw/seq_03/"]
  rect_sequences_path: ["data/34759_final_project_rect/seq_01/", "data/34759_final_project_rect/seq_02/", "data/34759_final_project_rect/seq_03/"]
  calibration_file: "data/34759_final_project_raw/calib_cam_to_cam.txt"
  rectified_images_path: "data/34759_final_project_rect/rectified_images/"

calibration:
  chessboard_size: [9, 6]
  square_size: 0.025  # in meters
  calibration_file_rect: "data/34759_final_project_rect/calib_cam_to_cam.txt"

detection:
  model: "yolov8"
  confidence_threshold: 0.5
  nms_threshold: 0.4

tracking:
  algorithm: "kalman"
  max_age: 30
  min_hits: 3

classification:
  model_path: "src/models/yolov8/yolov8.pt" # Remember to change this path based on your model
  input_size: 224

logging:
  config_file: "config/logging.yaml"
  
processing:
  use_rectified_data: true  # Set to false to process raw data

